### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by shyam2tayal** [shyam2tayal/micro-social-directory-using-angular-js#1]
randomuser.me API is not working so users are not being fetched. 
now they are giving only 1 user detail but we need many.
So need a different APi

**Comment by wiewioraseb** [comment]
I will take a look.

**Comment by dgrcode** [comment]
I just checked the API and it is working up to 5000 users. Where in your code are you calling the API so I can modify it and send a PR?

**Comment by wiewioraseb** [comment]
@shyam2tayal randomuser.me API was all good. One html tag was not closed and you were wrongly referring to nested json objects. #3

**Comment by dgrcode** [comment]
I found where your code is calling the API (at controllers/MainController.js) and I've checked that it is retrieving 50 different elements, as you would expect from the code.

The issue seems to be when displaying the info at index.html. I am debugging the page and I can see that there are 50 divs, one for each contact fetched from the API. However, those divs are not visible for some reason.

Could it be related with Angular?

**Comment by wiewioraseb** [comment]
@dgrcode I have just solved it. Regards.

**Comment by dgrcode** [comment]
@wiewioraseb great! :+1:  you should submit a pull request with the fixes then.
Regards

**Comment by wiewioraseb** [comment]
@dgrcode I did, or should I do it different way? You can see my PR in Pull Request tab.

**Comment by shyam2tayal** [comment]
@dgrcode @wiewioraseb  Actually when i first did that i all was working fine suddenly this happened . may be this is due to change in format of the API JSON object.

**Comment by shyam2tayal** [comment]
@dgrcode thanks man! you did it right !
